return {
	"neovim/nvim-lspconfig",
	dependencies = {
		"williamboman/mason.nvim",
		"williamboman/mason-lspconfig.nvim",
		"j-hui/fidget.nvim",
	},
	config = function()
		local cmp_lsp = require("cmp_nvim_lsp")
		local capabilities = vim.tbl_deep_extend(
			"force",
			{},
			vim.lsp.protocol.make_client_capabilities(),
			cmp_lsp.default_capabilities()
		)

		require("fidget").setup({})
		require("mason").setup()
		require("mason-lspconfig").setup({
			ensure_installed = {
				"lua_ls",
				"intelephense",
			},
			handlers = {
				function(server_name) -- default handler (optional)
					require("lspconfig")[server_name].setup({
						capabilities = capabilities,
					})
				end,
				["lua_ls"] = function()
					local lspconfig = require("lspconfig")
					lspconfig.lua_ls.setup({
						capabilities = capabilities,
						settings = {
							Lua = {
								runtime = { version = "Lua 5.1" },
								diagnostics = {
									globals = { "bit", "vim", "it", "describe", "before_each", "after_each" },
								},
							},
						},
					})
				end,
				["intelephense"] = function()
					local lspconfig = require("lspconfig")
					lspconfig.intelephense.setup({
						root_dir = lspconfig.util.root_pattern("composer.json", ".git", "wp-config.php"),
						capabilities = capabilities,
						settings = {
							intelephense = {
								files = {
									maxSize = 5000000,
								},
								stubs = {
									"amqp",
									"apache",
									"apcu",
									"bcmath",
									"blackfire",
									"bz2",
									"calendar",
									"cassandra",
									"com_dotnet",
									"Core",
									"couchbase",
									"crypto",
									"ctype",
									"cubrid",
									"curl",
									"date",
									"dba",
									"decimal",
									"dom",
									"ds",
									"enchant",
									"Ev",
									"event",
									"exif",
									"fann",
									"FFI",
									"ffmpeg",
									"fileinfo",
									"filter",
									"fpm",
									"ftp",
									"gd",
									"gearman",
									"geoip",
									"geos",
									"gettext",
									"gmagick",
									"gmp",
									"gnupg",
									"grpc",
									"hash",
									"http",
									"ibm_db2",
									"iconv",
									"igbinary",
									"imagick",
									"imap",
									"inotify",
									"interbase",
									"intl",
									"json",
									"judy",
									"ldap",
									"leveldb",
									"libevent",
									"libsodium",
									"libxml",
									"lua",
									"lzf",
									"mailparse",
									"mapscript",
									"mbstring",
									"mcrypt",
									"memcache",
									"memcached",
									"meminfo",
									"meta",
									"ming",
									"mongo",
									"mongodb",
									"mosquitto-php",
									"mqseries",
									"msgpack",
									"mssql",
									"mysql",
									"mysql_xdevapi",
									"mysqli",
									"ncurses",
									"newrelic",
									"oauth",
									"oci8",
									"odbc",
									"openssl",
									"parallel",
									"Parle",
									"pcntl",
									"pcov",
									"pcre",
									"pdflib",
									"PDO",
									"pdo_ibm",
									"pdo_mysql",
									"pdo_pgsql",
									"pdo_sqlite",
									"pgsql",
									"Phar",
									"phpdbg",
									"posix",
									"pspell",
									"pthreads",
									"radius",
									"rar",
									"rdkafka",
									"readline",
									"recode",
									"redis",
									"Reflection",
									"regex",
									"rpminfo",
									"rrd",
									"SaxonC",
									"session",
									"shmop",
									"SimpleXML",
									"snmp",
									"soap",
									"sockets",
									"sodium",
									"solr",
									"SPL",
									"SplType",
									"SQLite",
									"sqlite3",
									"sqlsrv",
									"ssh2",
									"standard",
									"stats",
									"stomp",
									"suhosin",
									"superglobals",
									"svn",
									"sybase",
									"sync",
									"sysvmsg",
									"sysvsem",
									"sysvshm",
									"tidy",
									"tokenizer",
									"uopz",
									"uv",
									"v8js",
									"wddx",
									"win32service",
									"winbinder",
									"wincache",
									"wordpress",
									"xcache",
									"xdebug",
									"xhprof",
									"xml",
									"xmlreader",
									"xmlrpc",
									"xmlwriter",
									"xsl",
									"xxtea",
									"yaf",
									"yaml",
									"yar",
									"zend",
									"Zend OPcache",
									"ZendCache",
									"ZendDebugger",
									"ZendUtils",
									"zip",
									"zlib",
									"zmq",
									"zookeeper",
								},
								environment = {
									includePaths = {
										"/usr/include/php",
										"~/.composer/vendor",
									},
								},
							},
						},
					})
				end,
			},
		})
		vim.diagnostic.config({
			-- update_in_insert = true,
			float = {
				focusable = false,
				style = "minimal",
				border = "rounded",
				source = "if_many",
				header = "",
				prefix = "",
			},
		})
	end,
}
